FROM python:3.9-alpine

ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/api

COPY ./requirements.txt /usr/src/api/requirements.txt

RUN pip install -r requirements.txt

COPY . /usr/src/api

CMD uvicorn main:api --host 0.0.0.0 --port 8000
